sudo: required
services:
  - docker

before-install:
  - docker build -t zulake/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true zulake/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "react-app"
  env: "React-app-env"
  bucket_name: "elasticbeanstalk-eu-north-1-089520470836"
  bucket_path: "react-app"
  on:
    branch: main
access_key_id: $ACCESS_KEY
secret_access_key: $SECRET_KEY
